```{r}
t <- read.table("/home/immd0754/Documents/R_things/qPCR/qPCR/rawdata.csv", sep=",")
t <- t[,5:8]

s <- c("Xrn1del", "Rpl39del", "Xrn1del_DSN", "Rpl39del_DSN1", "Rpl39del_DSN2")
sample_names <- rep(s, each=6)

other_names <- rep("standard", each=6)
other_names <- c(other_names, rep("NTC", each=2))
other_names <- rep(other_names, each=2)
ulku <- rep("ulku", each=12)

names_samples <- c(other_names, ulku, sample_names)


dilutions <- rep(c(10000, 20000), each=3)
dilutions <- rep(dilutions, times=5)

stand_dil <- rev(seq(1:6))
concentration <- c(stand_dil, 0,0 )
concentration <- c(rep(concentration, times=2), rep(NA, each=12), dilutions)

table2 <- cbind(names_samples, concentration, t)

colnames(table2)[3:6] <- c("ct", "average", "stdev/given conc", "determined conc")
```


```{r}
library("reshape2")
library("stats")
simple_table <- cbind(table2[1:6, 5], table2[1:6, 3], table2[9:14,3])
simple_table2 <- as.data.frame(cbind(rep(simple_table[,1], times=2), melt(simple_table[,2:3])[[3]]))
simple_table3 <- as.data.frame(cbind(log(simple_table2[,1]), simple_table2[,2]))

colnames(simple_table3) <- c("x", "y")

plot(simple_table3)
scatter.smooth(simple_table3)

curve <- lm(x~y, simple_table3)

```


```{r}
f_ct <- function(ct) {
  d <- (curve$coefficients[[2]]*ct) + curve$coefficients[[1]]
  de <- exp(d)
  return(de)
}


result_table <- table2[29:58, 1:3]

result2 <- cbind(result_table, f_ct(result_table[,3]))
result3 <- cbind(result2, result2[,4]*result2[,2])
colnames(result3)[4:5] <- c("ct", "pg/l")

final <- rep(1:10, each=3)
result3 <- cbind(final, result3)

final <- as.vector(by(result3$`pg/l`, INDICES = result3$final, FUN = mean))
final2 <- as.vector(by(result3$`pg/l`, INDICES = result3$final, FUN = sd))

```

